name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Or your main branch name

permissions:
  id-token: write
  pages: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm install # Or yarn install

      - name: Build Next.js app
        run: npx next build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out # Next.js will output the static files to the 'out' directory

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
